### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by philipp-r** [Spamty/blog#1]
Which one?
- MIT
- Creative Commons
- GPL
- Apache

Add this one:

```
Copyright (c) 2016 by 
[Spamty team](https://github.com/Spamty) &
[contributors](https://github.com/Spamty/GITHUBREPOSITORY/graphs/contributors)
```

**Comment by VagishVela** [comment]
Do you want people re-using content?

**Comment by philipp-r** [comment]
Use Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International for text/content.
Suggesting GPL, MIT for source code?!
